apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-client
  name: web-client
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
      Protocol: TCP
  selector:
    io.kompose.service: web-client
status:
  loadBalancer: {}
